### ISSUE TITLE
💄  Switch to light theme

### ISSUE THREAD

**Issue by Lyokolux** [Lyokolux/ux-typing-experiment#34]
Switch the app to the light theme. The website should be light theme first.

The dark theme can be reused through the media query
```css
@media (prefers-color-scheme: light/dark/no-preference) {  .themed {    background: white;    color: black;  }}
```
and CSS variables that keeps the proper value for each theme (light/dark)

for example: 
```css
/* defined on :root or body */
.theme-light {
  --text-color: white;
}

p {
  color: var(--text-color) // set to black on light theme or white on dark theme
}
```
